### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by TheAksh** [TimboKZ/exact-trie#1]
Hi Tim
We want to leverage the awesome Chonky library, but exact-trie is a dependency with a License that's not acceptable by the organization that I work at. Could you please change this license to MIT? Would be really helpful!

**Comment by TimboKZ** [comment]
Hi Akshay, I have just published `exact-trie@1.0.12`, which uses the MIT license. I will publish a new version of Chonky shortly.

**Comment by TheAksh** [comment]
Awesome, thank you so much!
